# Generated by Django 4.1.7 on 2023-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('release_date', models.CharField(max_length=20)),
                ('lte_exists', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
