# Generated by Django 4.1.7 on 2023-02-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_lte_exists_alter_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
